# Generated by Django 4.1 on 2023-02-01 03:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=50, verbose_name='型号')),
                ('name_zh', models.CharField(max_length=50, verbose_name='中文名称')),
                ('name_en', models.CharField(max_length=50, verbose_name='英文名称')),
                ('classification', models.SmallIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], verbose_name='设备分类')),
                ('Range', models.CharField(blank=True, max_length=50, verbose_name='范围')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='供应商')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_name', models.CharField(max_length=30, unique=True, verbose_name='位置名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eql', models.CharField(max_length=30, unique=True, verbose_name='设备编号')),
                ('sn', models.CharField(max_length=50, unique=True, verbose_name='序列号')),
                ('calibration_date', models.DateField(blank=True, null=True, verbose_name='校准日期')),
                ('calibration_due', models.DateField(blank=True, null=True, verbose_name='校准到期日期')),
                ('pm_date', models.DateField(blank=True, null=True, verbose_name='PM日期')),
                ('pm_due', models.DateField(blank=True, null=True, verbose_name='PM到期日期')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='释放日期')),
                ('status', models.SmallIntegerField(choices=[(1, '安装中'), (2, '使用中'), (3, '退休'), (4, '备用'), (5, '宁波设备')], verbose_name='设备状态')),
                ('retire_date', models.DateField(blank=True, null=True, verbose_name='退休日期')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.category', verbose_name='型号')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.place', verbose_name='位置')),
                ('primary_assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_assigned_instruments', to='instrument.user', verbose_name='首责任人')),
                ('secondary_assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_assigned_instruments', to='instrument.user', verbose_name='次责任人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.manufacturer', verbose_name='供应商'),
        ),
    ]
